package kou.taskthreshold;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class taskcounts implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("As count")
   private java.lang.Integer acount;
   private java.lang.Integer bcount;

   @org.kie.api.definition.type.Label("current assignee")
   private java.lang.String assigneefromrule;

   private java.lang.String specialization;

   public taskcounts()
   {
   }

   public java.lang.Integer getAcount()
   {
      return this.acount;
   }

   public void setAcount(java.lang.Integer acount)
   {
      this.acount = acount;
   }

   public java.lang.Integer getBcount()
   {
      return this.bcount;
   }

   public void setBcount(java.lang.Integer bcount)
   {
      this.bcount = bcount;
   }

   public java.lang.String getAssigneefromrule()
   {
      return this.assigneefromrule;
   }

   public void setAssigneefromrule(java.lang.String assigneefromrule)
   {
      this.assigneefromrule = assigneefromrule;
   }

   public java.lang.String getSpecialization()
   {
      return this.specialization;
   }

   public void setSpecialization(java.lang.String specialization)
   {
      this.specialization = specialization;
   }
   public String toString(){
       System.out.println(acount+"."+bcount+"."+assigneefromrule+"."+specialization);
       return (acount+"."+bcount+"."+assigneefromrule+"."+specialization);
   }
   

   public taskcounts(java.lang.Integer acount, java.lang.Integer bcount,
         java.lang.String assigneefromrule, java.lang.String specialization)
   {
      this.acount = acount;
      this.bcount = bcount;
      this.assigneefromrule = assigneefromrule;
      this.specialization = specialization;
   }

}